### ISSUE TITLE
Unable to install - mismatch between giiant's required version for yii2-gii and current verions

### ISSUE THREAD

**Issue by LarryTX** [schmunk42/yii2-giiant#251]
In a new installation of yii2 ver. 2.0.15 advanced-template, I am unable to install giiant. I have tried all three of these in composer.json:

- "schmunk42/yii2-giiant": "~0.10",
- "schmunk42/yii2-giiant": "@dev",
- "schmunk42/yii2-giiant": "@stable",

All three produce this stack of messages:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yiisoft/yii2-gii ~2.1.0 -> satisfiable by yiisoft/yii2-gii[2.1.0].
    - schmunk42/yii2-giiant 0.1.0 requires yiisoft/yii2-gii ~2.0.1 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
    - schmunk42/yii2-giiant 0.1.1 requires yiisoft/yii2-gii ~2.0.1 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
    - schmunk42/yii2-giiant 0.10.0 requires yiisoft/yii2-gii ~2.0.6 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
    - schmunk42/yii2-giiant 0.10.1 requires yiisoft/yii2-gii ~2.0.6 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
    - schmunk42/yii2-giiant 0.10.2 requires yiisoft/yii2-gii ~2.0.6 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
```
It would seem that giiant requires ver. 2.0.6 of gii, and the current installation is at 2.1.0.

Is there any workaround? Any timeline for an update?

**Comment by schmunk42** [comment]
A workaround could be to require `"yiisoft/yii2-gii": "2.1.0 as 2.0.999".

Could you give this a try and report back here.

@samdark @cebe Is there a special reason for `2.1.0` in gii and not `2.0.9`? I know we already discussed the semver issue for 2.x, but I am kinda confused why the framework will never have a 2.1 but extensions will.

**Comment by samdark** [comment]
Extensions were never tied to framework versions. See https://github.com/yiisoft/yii2-twig/releases for example.

**Comment by schmunk42** [comment]
But were there minor breaks? Is there something we need to consider before upgrading?

**Comment by samdark** [comment]
In the gii? It's not bootstrap 4 instead of bootstrap 3 so yes, there may be issues with custom panel styling.

**Comment by schmunk42** [comment]
@LarryTX I'd be waiting for feedback from your side, if this runs with gii 2.1 and BS4.

**Comment by LarryTX** [comment]
@schmunk42 Sorry to take so long getting back to you. Got called off to work on another emergency. Now, back to working on this one. Help me out here because I can't seem to get this one to work. I'll start with the result I'm getting; then, I'll give you what led up to it.(I have a feeling that I've made this one more difficult than it has to be.)
**Result**
```
D:\xampp\htdocs\memehope>yii batch
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "schmunk42\yii2-giiant\commands\BatchController".'

in D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php:433

Stack trace:
#0 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(365): yii\di\Container->getDependencies('schmunk42\\yii2-...')
#1 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('schmunk42\\yii2-...', Array, Array)
#2 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('schmunk42\\yii2-...', Array, Array)
#3 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(583): yii\BaseYii::createObject(Array, Array)
#4 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Module->createController('')
#5 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('batch', Array)
#6 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('batch', Array)
#7 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#8 D:\xampp\htdocs\memehope\yii(23): yii\base\Application->run()
#9 {main}
```
By the way, I'm using `batch` as opposed to `giiant-batch` as indicated in your instructions because `giiant-batch` produces a much more lengthy error trace which begins with:
```
D:\xampp\htdocs\memehope>yii giiant-batch
An Error occurred while handling another error:
ReflectionException: Class app\Modules\Network\Module does not exist in D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php:431
Stack trace:
#0 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(431): ReflectionClass->__construct('app\\Modules\\Net...')
#1 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(365): yii\di\Container->getDependencies('app\\Modules\\Net...')
#2 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('app\\Modules\\Net...', Array, Array)
#3 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('app\\Modules\\Net...', Array, Array)
#4 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(427): yii\BaseYii::createObject(Array, Array)
#5 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\controllers\HelpController.php(238): yii\base\Module->getModule('Network')
#6 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\controllers\HelpController.php(175): yii\console\controllers\HelpController->getModuleCommands(Object(yii\console\Application))
#7 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\UnknownCommandException.php(77): yii\console\controllers\HelpController->getCommands()
#8 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\ErrorHandler.php(35): yii\console\UnknownCommandException->getSuggestedAlternatives()
#9 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\console\ErrorHandler->renderException(Object(yii\console\UnknownCommandException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\console\UnknownCommandException))
#11 {main}
```
**Note:** Class `backend\Modules\Network\Module` ***does*** exists. Can't figure out how to make it use ***backend*** instead of ***app***.
**How I got here**
1. Standard Composer installation (`composer require ...`) won't work because of the version constraint, so I cloned the ***master*** branch into `/vendor/schmunk42` producing `/vendor/schmunk42/yii2-giiant`.
1. Changed `/vendor/schmunk42/yii2-giiant/composer.json` to `"require": ... "yiisoft/yii2-gii": "2.1.0 as 2.0.999" ...`.
1. Changed directory to `/vendor/schumk42/yi2-giiant`, and ran `composer update` which produced the following message:
```
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)                              Package operations: 0 installs, 0 updates, 0 removals
```
4. Made the following changes to /console/config/main.php:
```
$crudNs = '\backend\Modules\Network';

    return [
        'id'                  => 'app-console',
        'basePath'            => dirname(__DIR__),
        'bootstrap'           => ['log'],
        'controllerNamespace' => 'console\controllers',
        'aliases'             => [
            '@bower' => '@vendor/bower-asset',
            '@npm'   => '@vendor/npm-asset',
        ],
        'controllerMap'       => [
            'batch'   => [
                'class'                    => 'schmunk42\yii2-giiant\commands\BatchController',
                'overwrite'                => true,
                'modelNamespace'           => $crudNs . '\Models',
                'modelQueryNamespace'      => $crudNs . '\Models\Queries',
                'crudControllerNamespace'  => $crudNs . '\controllers',
                'crudSearchModelNamespace' => $crudNs . '\Models\Search',
                'crudViewPath'             => '@project\Modules\Network\views',
                'crudPathPrefix'           => '',
                'crudTidyOutput'           => true,
                'crudProviders'            => [
                    '\schmunk42\giiant\generators\crud\providers\extensions\EditorProvider',
                    '\schmunk42\giiant\generators\crud\providers\core\OptsProvider',
                ],
                'tablePrefix'              => '',
                'tables'                   => [
                    'network_connection_types',
                    'network_device_types',
                    'network_devices',
                    'network_wifi_connection_speeds',
                    'networks',
                ],
            ],
```
5. Ran `composer dump-autoload` which generated a message saying, `Generated autoload files containing 542 classes`.
1. Ran `yii batch` which produced the following error trace:
```
D:\xampp\htdocs\memehope>yii batch
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "schmunk42\yii2-giiant\commands\BatchController".'

in D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php:433

Stack trace:
#0 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(365): yii\di\Container->getDependencies('schmunk42\\yii2-...')
#1 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('schmunk42\\yii2-...', Array, Array)
#2 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('schmunk42\\yii2-...', Array, Array)
#3 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(583): yii\BaseYii::createObject(Array, Array)
#4 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Module->createController('')
#5 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('batch', Array)
#6 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('batch', Array)
#7 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#8 D:\xampp\htdocs\memehope\yii(23): yii\base\Application->run()
#9 {main}
```
I'm guessing that the error may occur because I cloned the extension instead of installing through composer and didn't know what else to do afterwards.

I'm wondering, if we can somehow work through all this, if the following dependencies won't create some problems:
*  "dmstr/yii2-bootstrap": "^0.1.2 || ^0.2.1",
* "dmstr/yii2-helpers": "*",
* "dmstr/yii2-db": "*",
In particular, `dmstr/yii2-bootstrap` doesn't appear to do anything at all itself, but it does have as a dependency, `"yiisoft/yii2-bootstrap": "^2.0.6"` rather than `"yiisoft/yii2-bootstrap4": "^2.0",`. Not sure if it matters since `composer update` doesn't appear to have installed these or anything else in the composer.json.

Anyway, if you can tell me how to proceed, I'll be happy to work on it.

**Comment by schmunk42** [comment]
> Standard Composer installation (composer require ...) won't work because of the version constraint,

You need to use ``"yiisoft/yii2-gii": "2.1.0 as 2.0.999".` in your project's (root) `composer.json` **NOT** in a vendor package.

**Comment by LarryTX** [comment]
That appears to have worked!

**Comment by LarryTX** [comment]
By the way, you have a number of annoying dependencies that don't show up until you have created things with giiant and attempt to make use of them. With regard to the Modules Generator, you get the following:
```
dmstr\web\traits\AccessBehaviorTrait not found in Modules.php
Class 'rmrevin\yii\fontawesome\FA' not found in index.php
```
It would be helpful if your instructions at least pointed out that you have to install these independently before making use of the files generated by giiant.

Please don't automatically load these as dependencies. I absolutely hate yii's AccessBehavior and always go with RBAC. As to font-awesome, like most users nowadays, I load it as part of my asset bundle. Actually, I load Font-awesome Pro. I'll try rmrevin's rmrevin\yii\fontawesome\NpmProAssetBundle, but I'm not sure if it offers enough to make me back out of what I've got installed.

**Comment by schmunk42** [comment]
> It would be helpful if your instructions at least pointed out that you have to install these independently before making use of the files generated by giiant.

I totally agree, these are leftovers from usage in *phd*, we need to clean this up.

> Please don't automatically load these as dependencies. I absolutely hate yii's AccessBehavior and always go with RBAC.

Actually our `AccessBehaviorTrait` is a way to make use of RBAC for controller in a generic way ;) https://github.com/dmstr/yii2-web/blob/master/src/traits/AccessBehaviorTrait.php - you might wanna have a look at it.

> As to font-awesome, like most users nowadays, I load it as part of my asset bundle. Actually, I load Font-awesome Pro. I'll try rmrevin's rmrevin\yii\fontawesome\NpmProAssetBundle, but I'm not sure if it offers enough to make me back out of what I've got installed.

Yeah, font awesome should be removed, also a leftover from the early days, when we thought AssetBundles will solve any problem. :roll_eyes:

**Comment by LarryTX** [comment]
Actually, I have looked a dmstr's AccessBehaviorTrait multiple times. I remember it often; every time I have to comment out your usage of it. When I said RBAC, I meant real, functional RBAC, i.e., RBAC built on the standard three database tables. I only consider database-driven RBAC.

**Comment by LarryTX** [comment]
I was able to use the Module generator successfully. However, as soon as I attempted to go the giiant Model generator, I got a fatal error that seems to derive from Gii. The trace is:
```
yii\base\ErrorException: Undefined index: class in D:\xampp\htdocs\memehope\vendor\schmunk42\yii2-giiant\src\helpers\SaveForm.php:61
Stack trace:
#0 D:\xampp\htdocs\memehope\vendor\schmunk42\yii2-giiant\src\helpers\SaveForm.php(61): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'D:\\xampp\\htdocs...', 61, Array)
#1 D:\xampp\htdocs\memehope\vendor\schmunk42\yii2-giiant\src\helpers\SaveForm.php(126): schmunk42\giiant\helpers\SaveForm::loadSavedForms('Giiant Model')
#2 D:\xampp\htdocs\memehope\vendor\schmunk42\yii2-giiant\src\generators\model\form.php(15): schmunk42\giiant\helpers\SaveForm::getSavedFormsJs('Giiant Model')
#3 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\View.php(348): require('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\View.php(257): yii\base\View->renderPhpFile('D:\\xampp\\htdocs...', Array)
#5 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2-gii\src\views\default\view.php(43): yii\base\View->renderFile('D:\\xampp\\htdocs...', Array)
#6 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\View.php(348): require('D:\\xampp\\htdocs...')
#7 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\View.php(257): yii\base\View->renderPhpFile('D:\\xampp\\htdocs...', Array)
#8 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('D:\\xampp\\htdocs...', Array, Object(yii\gii\controllers\DefaultController))
#9 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Controller.php(384): yii\base\View->render('view', Array, Object(yii\gii\controllers\DefaultController))
#10 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2-gii\src\controllers\DefaultController.php(72): yii\base\Controller->render('view', Array)
#11 [internal function]: yii\gii\controllers\DefaultController->actionView('giiant-model')
#12 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('view', Array)
#15 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('gii/default/vie...', Array)
#16 D:\xampp\htdocs\memehope\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#17 D:\xampp\htdocs\memehope\backend\web\index.php(17): yii\base\Application->run()
#18 {main}
```
Please let me know what to do next.

**Comment by schmunk42** [comment]
Could you double check the (POST) data which is sent by the form and how it's received on the server, somehow `class` is not found.

**Comment by LarryTX** [comment]
I will attempt to get you the POST data — as soon as I can get beyond the multiple, egregious problem that I've encountered by  attempting to use rmrevin's fontawesome extension. This is a perfect example of why you shouldn't try to force something like this on anyone. My application, like thousands of others, is an advanced template. In my advanced template site, I've got a node_modules folder that is on the same level as the backend, frontend, and vendor folders. I cannot and never have been interested in maintaining separate node_modules installations for the backend and frontend, and in my case, my separate storage, applications. One is enough, thank you.

Here's what rmrevin's extension's NpmProAssetBundle looks like:
```
class NpmProAssetBundle extends \yii\web\AssetBundle
{
    /**
     * @inherit
     */
    public $sourcePath = '@app/node_modules/@fortawesome/fontawesome-pro';

    /**
     * @inherit
     */
    public $css = [
        'css/all.min.css',
    ];

    /**
     * @inherit
     */
    public $publishOptions = [
        'only' => [
            'css/*',
            'webfonts/*',
        ],
    ];
}
```
Unfortunately, I installed this extension last night. When I pulled it up today, of course,  it totally failed with the following fatal error:
```
The file or directory to be published does not exist: D:\xampp\htdocs\memehope\backend/node_modules/@fortawesome/fontawesome-pro
```
So now, I'm going to have to clone his AssetBundle and rework it into something usable. But wait. I've got a backend theme that I'm using. There is no `'css/all.min.css',`. There's a `<theme-name>\css`. Guess, he was just trying to see how confused, frustrated, and angry he could make me. Like also including a `'webfonts/*',` in his AppBundle. I don't have any directory like that, don't intend to have one, and can't image why anyone would want such a thing. It's Yii, designed and built for web applications, and I have built a web application. Just what would I put in my desktopfonts directory as opposed to what I would use a webfonts directory for. Since it would be the height of idiocy on a website to have anything other than fonts that work on the web, a fonts directory will work just fine for me, and that's what I have.

Making all these presumptions about someone else's web application is just how the developers of extensions make it totally impossible for neophyte developers to create anything in the Yii2 framework. I must admit that Revin does provide good advanced documentation for his extensions (at least those for which the documentation is available in English), but he totally misses it on the very most basic level, the very level at which the most basic of users will be tripped up, throw their hands up, and run to something else, some other framework.

As for me, I guess I'll spend the next several days trying to refactor his extension into something usable. (No doubt, the lack of a webfonts directory will cause some inscrutable error that will cost me countless hours of work.) When I get that finished, I'll try to get you the POST data. This will be a neverendingsaga.

**Comment by schmunk42** [comment]
@LarryTX Could you give this branch a try https://github.com/schmunk42/yii2-giiant/tree/feature/removed-fontawesome

Lessons learned, we'll use fewer deps in the future, I also noticed there there are dev-dependencies which are actually one required for testing *the generated code*, which is a pretty special case.

**Comment by LarryTX** [comment]
Will do. Probably this afternoon.

Larry E. Lutz

**Comment by LarryTX** [comment]
Tobias, some preliminary observations as I worked through this. On the Module generate/create page https:/<domain>/gii/default/view?id=giiant-module)(, this is what appears at the top of the page:
```
yii\web\Request#1 ( [enableCsrfValidation] => true [csrfParam] => '_csrf-backend' [csrfCookie] => [ 'httpOnly' => true ] [enableCsrfCookie] => true [enableCookieValidation] => true [cookieValidationKey] => '5dUUdfzgGE7IKrVNl5nrtg1PFKwAMfHm' [methodParam] => '_method' [parsers] => [] [trustedHosts] => [] [secureHeaders] => [ 0 => 'X-Forwarded-For' 1 => 'X-Forwarded-Host' 2 => 'X-Forwarded-Proto' 3 => 'Front-End-Https' 4 => 'X-Rewrite-Url' ] [ipHeaders] => [ 0 => 'X-Forwarded-For' ] [secureProtocolHeaders] => [ 'X-Forwarded-Proto' => [ 0 => 'https' ] 'Front-End-Https' => [ 0 => 'on' ] ] [yii\web\Request:_cookies] => yii\web\CookieCollection#2 ( [readOnly] => true [yii\web\CookieCollection:_cookies] => [ '_identity-backend' => yii\web\Cookie#3 ( [name] => '_identity-backend' [value] => '[1,\"0WI9OHvZaPBI7YOTbsKShKzGmKZgjJCz\",7776000]' [domain] => '' [expire] => null [path] => '/' [secure] => false [httpOnly] => true ) '_csrf-backend' => yii\web\Cookie#4 ( [name] => '_csrf-backend' [value] => 'uBJoVScSRtC4Rx16oOEXpMOqBSxILwLe' [domain] => '' [expire] => null [path] => '/' [secure] => false [httpOnly] => true ) ] ) [yii\web\Request:_headers] => yii\web\HeaderCollection#5 ( [yii\web\HeaderCollection:_headers] => [ 'host' => [ 0 => 'admin.memehope.lcl' ] 'user-agent' => [ 0 => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0' ] 'accept' => [ 0 => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' ] 'accept-language' => [ 0 => 'en-US,en;q=0.5' ] 'accept-encoding' => [ 0 => 'gzip, deflate, br' ] 'referer' => [ 0 => 'https://admin.memehope.lcl/gii' ] 'dnt' => [ 0 => '1' ] 'connection' => [ 0 => 'keep-alive' ] 'cookie' => [ 0 => '_identity-backend=1fd81b1dc7f7f8da710dcab81217adb916561da49f1ae2b8baa54a619649a48da%3A2%3A%7Bi%3A0%3Bs%3A17%3A%22_identity-backend%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%220WI9OHvZaPBI7YOTbsKShKzGmKZgjJCz%22%2C7776000%5D%22%3B%7D; advanced-backend=olhq583302gbshk4n14lgtjtoj; _csrf-backend=2f75d9504374bef294eeda5e84adb0fade9c7fe2cfe571ab4fd428d9b2158d7ea%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22uBJoVScSRtC4Rx16oOEXpMOqBSxILwLe%22%3B%7D' ] 'upgrade-insecure-requests' => [ 0 => '1' ] ] ) [yii\web\Request:_rawBody] => '' [yii\web\Request:_bodyParams] => [] [yii\web\Request:_queryParams] => null [yii\web\Request:_hostInfo] => null [yii\web\Request:_hostName] => null [yii\web\Request:_baseUrl] => '' [yii\web\Request:_scriptUrl] => '/index.php' [yii\web\Request:_scriptFile] => null [yii\web\Request:_pathInfo] => 'gii/default/view' [yii\web\Request:_url] => '/gii/default/view?id=giiant-module' [yii\web\Request:_port] => null [yii\web\Request:_securePort] => null [yii\web\Request:_contentTypes] => null [yii\web\Request:_languages] => null [yii\web\Request:_csrfToken] => null [yii\base\Request:_isConsoleRequest] => null [yii\base\Component:_events] => [] [yii\base\Component:_eventWildcards] => [] [yii\base\Component:_behaviors] => null [yii\base\Request:_scriptFile] => null )
```
Same thing occurs on Model generation and CRUD generation. If you need copies of those, let me know, and I'll send them on. As you might expect, when you complete the form and submit, it returns with an even larger amount of this stuff.

As to whether it works otherwise, drum roll please, it's perfect.

**Comment by schmunk42** [comment]
>  this is what appears at the top of the page

Is this shown in the browser, could you post a screenshot? 
Maybe some debug output in your project.
Actually The forms/create pages look good to me.

**Comment by LarryTX** [comment]
You’re right the forms/create pages all look great. Now, if I’d just follow my instincts. I started to attach screenshots before. The problem is that the text that spills out at the top pretty much takes up all of my 24” monitor. (When I scroll down, the form always looks great.) Anyway, here’s what I’ve attached:


  1.  Giiant Model 1: The Giiant model creation page when I first get to it, before completing the form.
  2.  Giiant Model Debug 1: The debug info from #1.
  3.  Giiant Model 2: The Giiant model creation page after completing the form and clicking Preview.
  4.  Giiant Model Debug 2: The debug info from #3.
  5.  Giiant Model 3: The Giiant model creation page after clicking Generate.
  6.  Giiant Model Debug 3: The debug info from #5.

Hope all that makes sense. If I can explain it any further, just let me know.

Also, I only included screenshots from Model generation. If you’d like me to do screenshots from Module and CRUD, just let me know.

Larry E. Lutz

**Comment by schmunk42** [comment]
There are no screenshots attached, you might need to add them on GitHub directly.

**Comment by LarryTX** [comment]
Hope this works.
![Giiant Model Debug 3](https://user-images.githubusercontent.com/20743/57153536-2d122380-6d9c-11e9-9a8c-9d516dacb9f6.png)
![Giiant Model 1](https://user-images.githubusercontent.com/20743/57153537-2d122380-6d9c-11e9-9ec3-8f70f0287a3f.png)
![Giiant Model 2](https://user-images.githubusercontent.com/20743/57153538-2d122380-6d9c-11e9-81d5-95fbd72bdaa8.png)
![Giiant Model 3](https://user-images.githubusercontent.com/20743/57153539-2daaba00-6d9c-11e9-8ec0-c2c344597a06.png)
![Giiant Model Debug 1](https://user-images.githubusercontent.com/20743/57153540-2daaba00-6d9c-11e9-8ae2-1ff74229b58d.png)
![Giiant Model Debug 2](https://user-images.githubusercontent.com/20743/57153542-2daaba00-6d9c-11e9-91ed-63bd0184e208.png)

**Comment by schmunk42** [comment]
Could you search in your code for `var_dump` and `VarDumper`, this really looks like some debug output (on your side).
