### ISSUE TITLE
Getting unknown property: schmunk42\giiant\crud\Generator::moduleID

### ISSUE THREAD

**Issue by dutchakdev** [schmunk42/yii2-giiant#38]
```
PHP User Error – yii\base\ErrorException

Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: schmunk42\giiant\crud\Generator::moduleID'

in /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/Component.php:143

Stack trace:
#0 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/helpers/BaseHtml.php(1838): yii\base\Component->__get('moduleID')
#1 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/helpers/BaseHtml.php(1139): yii\helpers\BaseHtml::getAttributeValue(Object(schmunk42\giiant\crud\Generator), 'moduleID')
#2 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/helpers/BaseHtml.php(1160): yii\helpers\BaseHtml::activeInput('text', Object(schmunk42\giiant\crud\Generator), 'moduleID', Array)
#3 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/widgets/ActiveField.php(177): yii\helpers\BaseHtml::activeTextInput(Object(schmunk42\giiant\crud\Generator), 'moduleID', Array)
#4 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/widgets/ActiveField.php(149): yii\widgets\ActiveField->render()
#5 /private/var/www/xxx.xxx/vendor/schmunk42/yii2-giiant/crud/form.php(12): yii\widgets\ActiveField->__toString()
#6 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/View.php(325): require('/private/var/ww...')
#7 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/private/var/ww...', Array)
#8 /private/var/www/xxx.xxx/vendor/yiisoft/yii2-gii/views/default/view.php(38): yii\base\View->renderFile('/private/var/ww...', Array)
#9 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/View.php(325): require('/private/var/ww...')
#10 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/private/var/ww...', Array)
#11 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/private/var/ww...', Array, Object(yii\gii\controllers\DefaultController))
#12 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/Controller.php(367): yii\base\View->render('view', Array, Object(yii\gii\controllers\DefaultController))
#13 /private/var/www/xxx.xxx/vendor/yiisoft/yii2-gii/controllers/DefaultController.php(56): yii\base\Controller->render('view', Array)
#14 [internal function]: yii\gii\controllers\DefaultController->actionView('giiant-crud')
#15 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#16 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#17 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('view', Array)
#18 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('gii/default/vie...', Array)
#19 /private/var/www/xxx.xxx/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /private/var/www/xxx.xxx/backend/web/index.php(18): yii\base\Application->run()
#21 {main}
```

in vendor/schmunk42/yii2-giiant/crud/Generator.php

```
    public $moduleID;
```

**Comment by schmunk42** [comment]
Double checked ... fix available in 0.1.1 - but use 0.2.0 if possible or create an issue if there are problems with accessing the application config
